server:
  port: 56700
spring:
  application:
    name: my-zuul
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.18.240:3306/kytms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

  redis:
    database: 0
    host: 192.168.18.210
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 50000
    password: dmcn

eureka:
  client:
    service-url:
      defaultZone: http://192.168.18.210:56798/eureka/,http://192.168.18.210:56799/eureka/
  instance:
    prefer-ip-address: true
    instance-id: my_zuul8088


ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enabled: true


zuul:
  routes:
    jwxt-teacher:
      path: /teacher/**
      service-id: jwxt-teacher
    jwxt-learner:
      path: /student/**
      service-id: jwxt-learner
    ignored-services: '*'
#  ratelimit: # 全局限流
#    enabled: true #开启限流
#    behind-proxy: true #通过代理来执行限流
#    default-policy: #设置限流规则
#      limit: 150 #在单元时间内允许访问2次
#      quota: 60 #在单元时间内所有请求加起来不得超过5秒
#      refresh-interval: 1 #单元时间 1秒之后重新计数
#      type:
#        - user
#        - origin
#        - url

# 配置断路器
hystrix:
  command:
    default:
      circuitBreaker:
        enabled: true   #启动断路器
        requestVolumeThreshold: 10  #请求数达到后才计算
        sleepWindowInMilliseconds: 10000  #休眠时间
        errorThresholdPercentage: 50    #错误率
      execution:
        isolation:
          thread:   #熔断策略:线程
            timeoutInMilliseconds: 70000  #设置请求超时时间（默认是一秒） 超时后会走后备方法



# 开启了所有健康监测的访问接口，默认只开启了health和info，也开启了hystrix的仪表盘访问
management:
  endpoints:
    web:
      exposure:
        include: '*'

#spring:
#  cloud:
#    config:
#      #uri: http://192.168.18.210:8888
#      uri: http://localhost:8888
#      label: master
#      name: application-zuul
#      profile: dev   # 指定环境

