server:
  port: 56700
spring:
  application:
    name: my-zuul
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kytms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    #url: jdbc:mysql://192.168.5.240:3306/kytms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root





eureka:
  client:
    service-url:
      defaultZone: http://localhost:56798/eureka/,http://localhost:56799/eureka/
  instance:
    prefer-ip-address: true
    instance-id: my_zuul8088




ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enabled: true

zuul:
  routes:
    jwxt-teacher:
      path: /teacher/**
      service-id: jwxt-teacher
    jwxt-learner:
      path: /student/**
      service-id: jwxt-learner
    ignored-services: '*'



# 配置断路器
hystrix:
  command:
    default:
      circuitBreaker:
        enabled: true   #启动断路器
        requestVolumeThreshold: 10  #请求数达到后才计算
        sleepWindowInMilliseconds: 10000  #休眠时间
        errorThresholdPercentage: 50    #错误率
      execution:
        isolation:
          thread:   #熔断策略:线程
            timeoutInMilliseconds: 5000  #设置请求超时时间（默认是一秒） 超时后会走后备方法



# 开启了所有健康监测的访问接口，默认只开启了health和info，也开启了hystrix的仪表盘访问
management:
  endpoints:
    web:
      exposure:
        include: '*'

