server:
  port: 8888


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kytms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    #url: jdbc:mysql://192.168.5.240:3306/kytms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  application:
    name: jwxt-config #指定服务名

  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/hanxuesong123/jwxt-configuration.git
          search-paths: config
          username: 1323232302@qq.com
          passphrase: hanzhibin1


eureka:
  client:
    service-url:
      defaultZone : http://localhost:56798/eureka/,http://localhost:56799/eureka/
      #defaultZone : http://192.168.5.210:56798/eureka/,http://192.168.5.210:56799/eureka/  #我们要把该项目注册到哪个服务中心上
  instance:
    prefer-ip-address: true
    instance-id: config #在注册中心显示的微服务的名称



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/jwxt/*/mapper/*.xml