server:
  port: 56710


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/kytms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    url: jdbc:mysql://192.168.5.240:3306/kytms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  application:
    name: jwxt-teacher #指定服务名

  redis:
    database: 0
    host: 192.168.5.210
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 50000
    password: dmcn


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/jwxt/*/mapper/*.xml

ftp:
  host: 192.168.5.210
  port: 22
  username: root
  password: dmcn@123

eureka:
  client:
    service-url:
      defaultZone : http://localhost:56798/eureka/,http://localhost:56799/eureka/
      #defaultZone : http://192.168.5.210:56798/eureka/,http://192.168.5.210:56799/eureka/  #我们要把该项目注册到哪个服务中心上
  instance:
    prefer-ip-address: true
    instance-id: teacher #在注册中心显示的微服务的名称

#feign的配置，连接超时及读取超时配置
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: basic

#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000
#  eureka:
#    enabled: true