server:
  port: 56710


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.18.240:3306/kytms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  application:
    name: jwxt-teacher #指定服务名

  redis:
    database: 0
    host: 192.168.18.210
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 50000
    password: dmcn

  mail:
    host: smtp.qq.com
    username: 2833785445@qq.com
    password: coksvbkjoemwddda
    default-encoding: UTF-8
#    port: 465
#    properties:
#      mail:
#        smtp:
#          ssl:
#            enable: true


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/jwxt/*/mapper/*.xml

ftp:
  host: 192.168.18.210
  port: 22
  username: root
  password: dmcn@123

eureka:
  client:
    service-url:
      defaultZone : http://192.168.18.210:56798/eureka/,http://192.168.18.210:56799/eureka/
  instance:
    prefer-ip-address: true
    instance-id: teacher #在注册中心显示的微服务的名称


#spring:
#  cloud:
#    config:
#      uri: http://localhost:8888
#      #uri: http://192.168.18.210:8888
#      label: master
#      name: application-teacher
#      profile: dev   # 指定环境
